import type { Metadata, Viewport } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { AnalyticsGate } from "./AnalyticsGate";
import { ServiceWorkerRegistrar } from "../components/ServiceWorkerRegistrar";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// Portrait apple-touch-startup-image set (generated by
// scripts/generate-pwa-assets.mjs). iOS only applies exact media matches.
const appleSplash = (w: number, h: number, scale: number) => ({
  url: `/splash/splash-${w * scale}x${h * scale}.png`,
  media: `(device-width: ${w}px) and (device-height: ${h}px) and (-webkit-device-pixel-ratio: ${scale}) and (orientation: portrait)`,
});

export const metadata: Metadata = {
  title: "calendar a day puzzle",
  description: "A daily puzzle where you place shapes to reveal today's date",
  // Safari prefers apple-touch-icon over manifest icons; keep them consistent.
  icons: {
    apple: "/icons/apple-touch-icon.png",
  },
  appleWebApp: {
    capable: true,
    title: "Caladay",
    // "default" + themeColor renders the standalone status bar in parchment
    // with dark text; black-translucent would give white (invisible) text.
    statusBarStyle: "default",
    startupImage: [
      appleSplash(375, 667, 2), // SE 2/3
      appleSplash(375, 812, 3), // X/XS/11 Pro/12-13 mini
      appleSplash(414, 896, 2), // XR/11
      appleSplash(414, 896, 3), // XS Max/11 Pro Max
      appleSplash(390, 844, 3), // 12/13/14
      appleSplash(393, 852, 3), // 14 Pro/15/15 Pro/16
      appleSplash(428, 926, 3), // 12/13 Pro Max/14 Plus
      appleSplash(430, 932, 3), // 14 Pro Max/15 Plus/15 Pro Max/16 Plus
      appleSplash(402, 874, 3), // 16 Pro
      appleSplash(440, 956, 3), // 16 Pro Max
    ],
  },
  formatDetection: {
    // The board is full of bare numbers; stop iOS from linkifying them.
    telephone: false,
  },
  other: {
    // Next emits the standard mobile-web-app-capable meta; iOS before 17.4
    // only honors the apple-prefixed variant, so ship both.
    "apple-mobile-web-app-capable": "yes",
  },
};

export const viewport: Viewport = {
  width: "device-width",
  initialScale: 1,
  // Prevent pinch/double-tap zoom from fighting the drag interactions,
  // and extend under the notch (safe areas handled via env() padding).
  maximumScale: 1,
  userScalable: false,
  viewportFit: "cover",
  themeColor: "#f2ede7",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
        <AnalyticsGate />
        <ServiceWorkerRegistrar />
      </body>
    </html>
  );
}
